# Generated by Django 2.2.5 on 2022-01-15 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=15)),
                ('node_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight', models.IntegerField()),
                ('Source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source', to='network.NodeDescription')),
                ('Target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Target', to='network.NodeDescription')),
            ],
        ),
    ]
