# Generated by Django 2.2.5 on 2022-01-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='NodeDescription',
        ),
    ]
