# Generated by Django 2.2.5 on 2022-01-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0002_auto_20220115_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkEdges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(blank=True, db_column='Source', null=True)),
                ('target', models.TextField(blank=True, db_column='Target', null=True)),
                ('weight', models.IntegerField(blank=True, db_column='Weight', null=True)),
            ],
            options={
                'db_table': 'network_edges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.TextField(blank=True, null=True)),
                ('node_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'network_nodes',
                'managed': False,
            },
        ),
    ]
