# Generated by Django 2.2.5 on 2022-01-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20220115_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='Source',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='network',
            name='Target',
            field=models.TextField(),
        ),
    ]
