# Generated by Django 2.2.5 on 2022-01-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20220115_2223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Network',
            new_name='NetworkEdge',
        ),
        migrations.RenameModel(
            old_name='NodeDescription',
            new_name='NetworkNode',
        ),
    ]
