# Generated by Django 2.2.5 on 2022-01-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_bnetworkedge_bnetworknode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bnetworkedge',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bnetworknode',
            options={'managed': True},
        ),
    ]
