# Generated by Django 2.2.5 on 2022-01-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20220120_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnetworknode',
            name='is_virus_targets_all_viruses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bnetworknode',
            name='is_virus_targets_hiv_ppi',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bnetworknode',
            name='is_virus_targets_hiv_rnai',
            field=models.IntegerField(null=True),
        ),
    ]
